name = "nola_tweets_worker"
type = "javascript"

account_id = "YOUR_CLOUDFLARE_ACCOUNT_ID"
workers_dev = true
compatibility_date = "2025-12-09"

kv_namespaces = [
  { binding = "TWEETS_KV", id = "YOUR_KV_NAMESPACE_ID" }
]

# You don't put your token here; it's in GitHub secrets or Cloudflare secret
